<a href="https://colab.research.google.com/github/camilasilva-1/analise-precos-gasolina-br/blob/main/analise_precos_gasolina_br.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

df_2000 = pd.read_csv('gasolina_2000_.csv')
df_2010 = pd.read_csv('gasolina_2010_.csv', low_memory=False)

In [2]:
df_2000.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082

In [4]:
df_2000.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42638 entries, 0 to 42637
Data columns (total 19 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     42638 non-null  int64
 1   DATA INICIAL                   42638 non-null  object
 2   DATA FINAL                     42638 non-null  object
 3   REGIÃO                         42638 non-null  object
 4   ESTADO                         42638 non-null  object
 5   PRODUTO                        42638 non-null  object
 6   NÚMERO DE POSTOS PESQUISADOS   42638 non-null  int64
 7   UNIDADE DE MEDIDA              42638 non-null  object
 8   PREÇO MÉDIO REVENDA            42638 non-null  float64
 9   DESVIO PADRÃO REVENDA          42638 non-null  float64
 10  PREÇO MÍNIMO REVENDA           42638 non-null  float64
 11  PREÇO MÁXIMO REVENDA           42638 non-null  float64
 12  MARGEM MÉDIA REVENDA           42638 non-null  object
 13  COEF DE VARIAÇÃO REVENDA       42638 non-null  float64
 14  PREÇO MÉDIO DISTRIBUIÇÃO       42638 non-null  object
 15  DESVIO PADRÃO DISTRIBUIÇÃO     42638 non-null  object
 16  PREÇO MÍNIMO DISTRIBUIÇÃO      42638 non-null  object
 17  PREÇO MÁXIMO DISTRIBUIÇÃO      42638 non-null  object
 18  COEF DE VARIAÇÃO DISTRIBUIÇÃO  42638 non-null  object
dtypes: float64(5), int64(2), object(12)
memory usage: 6.2+ MB

In [5]:
df = pd.concat([df_2000, df_2010], ignore_index=True)

In [6]:
df.shape

(120823, 19)

In [7]:
df = df.drop(columns=['Unnamed: 0'])

In [8]:
df.columns

Index(['DATA INICIAL', 'DATA FINAL', 'REGIÃO', 'ESTADO', 'PRODUTO',
       'NÚMERO DE POSTOS PESQUISADOS', 'UNIDADE DE MEDIDA',
       'PREÇO MÉDIO REVENDA', 'DESVIO PADRÃO REVENDA', 'PREÇO MÍNIMO REVENDA',
       'PREÇO MÁXIMO REVENDA', 'MARGEM MÉDIA REVENDA',
       'COEF DE VARIAÇÃO REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO',
       'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO',
       'PREÇO MÁXIMO DISTRIBUIÇÃO', 'COEF DE VARIAÇÃO DISTRIBUIÇÃO'],
      dtype='object')

In [10]:
terceira_entrada = df['DATA INICIAL'].iloc[2]
print(terceira_entrada)
print(type(terceira_entrada))

2004-05-09
<class 'str'>

In [11]:
df['DATA INICIAL'] = pd.to_datetime(df['DATA INICIAL'])
df['DATA FINAL'] = pd.to_datetime(df['DATA FINAL'])

In [12]:
df.dtypes

DATA INICIAL                     datetime64[ns]
DATA FINAL                       datetime64[ns]
REGIÃO                                   object
ESTADO                                   object
PRODUTO                                  object
NÚMERO DE POSTOS PESQUISADOS              int64
UNIDADE DE MEDIDA                        object
PREÇO MÉDIO REVENDA                     float64
DESVIO PADRÃO REVENDA                   float64
PREÇO MÍNIMO REVENDA                    float64
PREÇO MÁXIMO REVENDA                    float64
MARGEM MÉDIA REVENDA                     object
COEF DE VARIAÇÃO REVENDA                float64
PREÇO MÉDIO DISTRIBUIÇÃO                 object
DESVIO PADRÃO DISTRIBUIÇÃO               object
PREÇO MÍNIMO DISTRIBUIÇÃO                object
PREÇO MÁXIMO DISTRIBUIÇÃO                object
COEF DE VARIAÇÃO DISTRIBUIÇÃO            object
dtype: object

In [13]:
df['ANO_MES'] = df['DATA FINAL'].dt.strftime('%Y-%m')

In [14]:
df['ANO'] = df['DATA FINAL'].dt.year

In [15]:
df[['DATA FINAL', 'ANO_MES', 'ANO']].head()

  DATA FINAL  ANO_MES   ANO
0 2004-05-15  2004-05  2004
1 2004-05-15  2004-05  2004
2 2004-05-15  2004-05  2004
3 2004-05-15  2004-05  2004
4 2004-05-15  2004-05  2004

In [16]:
df['PRODUTO'].value_counts()

PRODUTO
GASOLINA COMUM        23570
GLP                   23561
ETANOL HIDRATADO      23440
ÓLEO DIESEL           21194
GNV                   14469
ÓLEO DIESEL S10        9113
OLEO DIESEL S10        2376
OLEO DIESEL            2351
GASOLINA ADITIVADA      749
Name: count, dtype: int64

In [17]:
gasolina_comum = df[df['PRODUTO'] == 'GASOLINA COMUM'].copy()

In [18]:
gasolina_comum.shape

(23570, 20)

In [19]:
ago_2008 = gasolina_comum[gasolina_comum['ANO_MES'] == '2008-08']

In [20]:
preco_medio_ago_2008 = ago_2008['PREÇO MÉDIO REVENDA'].mean()
print(preco_medio_ago_2008)

2.6012444444444442

In [22]:
maio_2014_sp = gasolina_comum[
    (gasolina_comum['ANO_MES'] == '2014-05') &
    (gasolina_comum['ESTADO'] == 'SAO PAULO')
]

In [23]:
gasolina_comum['ESTADO'].unique()

array(['DISTRITO FEDERAL', 'GOIAS', 'MATO GROSSO', 'MATO GROSSO DO SUL',
       'ALAGOAS', 'BAHIA', 'CEARA', 'MARANHAO', 'PARAIBA', 'PERNAMBUCO',
       'PIAUI', 'RIO GRANDE DO NORTE', 'SERGIPE', 'ACRE', 'AMAPA',
       'AMAZONAS', 'PARA', 'RONDONIA', 'RORAIMA', 'TOCANTINS',
       'ESPIRITO SANTO', 'MINAS GERAIS', 'RIO DE JANEIRO', 'SAO PAULO',
       'PARANA', 'RIO GRANDE DO SUL', 'SANTA CATARINA'], dtype=object)

In [24]:
preco_medio_sp_mai2014 = maio_2014_sp['PREÇO MÉDIO REVENDA'].mean()
print(preco_medio_sp_mai2014)

2.8822

In [25]:
acima_de_5 = gasolina_comum[gasolina_comum['PREÇO MÉDIO REVENDA'] > 5.00]

In [26]:
estados_acima_de_5 = sorted(acima_de_5['ESTADO'].unique())
print(estados_acima_de_5)

['ACRE', 'ALAGOAS', 'AMAZONAS', 'BAHIA', 'CEARA', 'DISTRITO FEDERAL', 'ESPIRITO SANTO', 'GOIAS', 'MARANHAO', 'MATO GROSSO', 'MATO GROSSO DO SUL', 'MINAS GERAIS', 'PARA', 'PARAIBA', 'PARANA', 'PERNAMBUCO', 'PIAUI', 'RIO DE JANEIRO', 'RIO GRANDE DO NORTE', 'RIO GRANDE DO SUL', 'RONDONIA', 'RORAIMA', 'SANTA CATARINA', 'SAO PAULO', 'SERGIPE', 'TOCANTINS']

In [27]:
primeira_data_acima_5 = acima_de_5.groupby('ESTADO')['DATA FINAL'].min().sort_values()
print(primeira_data_acima_5)

ESTADO
ACRE                  2018-05-26
RIO DE JANEIRO        2018-06-09
TOCANTINS             2018-09-29
RIO GRANDE DO NORTE   2021-01-30
DISTRITO FEDERAL      2021-02-13
BAHIA                 2021-02-20
RIO GRANDE DO SUL     2021-02-20
ALAGOAS               2021-02-20
PIAUI                 2021-02-20
MINAS GERAIS          2021-02-20
PARA                  2021-02-20
CEARA                 2021-02-20
MATO GROSSO DO SUL    2021-02-20
SERGIPE               2021-02-27
PARAIBA               2021-02-27
AMAZONAS              2021-02-27
PERNAMBUCO            2021-02-27
MARANHAO              2021-02-27
GOIAS                 2021-02-27
ESPIRITO SANTO        2021-02-27
RONDONIA              2021-02-27
SANTA CATARINA        2021-02-27
MATO GROSSO           2021-03-06
RORAIMA               2021-03-06
SAO PAULO             2021-03-06
PARANA                2021-03-06
Name: DATA FINAL, dtype: datetime64[ns]

In [28]:
sul_2012 = gasolina_comum[
    (gasolina_comum['REGIÃO'] == 'SUL') &
    (gasolina_comum['ANO'] == 2012)
]

In [29]:
media_sul_2012 = sul_2012['PREÇO MÉDIO REVENDA'].mean()
print(media_sul_2012)

2.7214423076923073

In [30]:
sul_2012.groupby('ESTADO')['PREÇO MÉDIO REVENDA'].mean()

ESTADO
PARANA               2.684731
RIO GRANDE DO SUL    2.759308
SANTA CATARINA       2.720288
Name: PREÇO MÉDIO REVENDA, dtype: float64

In [31]:
rj = gasolina_comum[gasolina_comum['ESTADO'] == 'RIO DE JANEIRO']

In [32]:
preco_medio_rj_por_ano = rj.groupby('ANO')['PREÇO MÉDIO REVENDA'].mean()
print(preco_medio_rj_por_ano)

ANO
2004    2.171939
2005    2.338588
2006    2.561365
2007    2.532077
2008    2.546731
2009    2.564980
2010    2.647788
2011    2.832698
2012    2.852827
2013    2.995442
2014    3.132115
2015    3.537471
2016    3.917736
2017    4.102308
2018    4.855077
2019    4.855096
2020    4.761295
2021    5.588778
Name: PREÇO MÉDIO REVENDA, dtype: float64

In [33]:
variacao_percentual = preco_medio_rj_por_ano.pct_change() * 100

In [34]:
tabela_variacao_rj = pd.DataFrame({
    'preco_medio': preco_medio_rj_por_ano,
    'variacao_%_ano_a_ano': variacao_percentual
})
print(tabela_variacao_rj)

      preco_medio  variacao_%_ano_a_ano
ANO
2004     2.171939                   NaN
2005     2.338588              7.672813
2006     2.561365              9.526138
2007     2.532077             -1.143471
2008     2.546731              0.578728
2009     2.564980              0.716575
2010     2.647788              3.228425
2011     2.832698              6.983551
2012     2.852827              0.710588
2013     2.995442              4.999090
2014     3.132115              4.562701
2015     3.537471             12.941899
2016     3.917736             10.749637
2017     4.102308              4.711187
2018     4.855077             18.349897
2019     4.855096              0.000396
2020     4.761295             -1.932005
2021     5.588778             17.379353